### ISSUE TITLE
Coding Standards and Contribution Guidelines

### ISSUE THREAD

**Issue by cheelahim** [venta/venta#2]
Please consider publishing the project Coding Standards as well as the Contribution Guidelines to standardize the code base from the very beginning of the project life cycle and make contribution process more transparent.
It would be great to join [PHP-FIG](http://www.php-fig.org/) and have a code base complied with the latest [PHP Standards Recommendations](http://www.php-fig.org/psr/).

**Comment by kzsw** [comment]
PSR it is ;)
